
version: 2

models:
    - name: example__my_first_dbt_model
      description: "A starter dbt model description."
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: example__my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            tags:
              - test_tag
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
